import { User, Wallet, Expense, CompanyExpense } from "@/types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@applywizz.com",
    role: "cfo",
  },
  {
    id: "2",
    name: "Priya Singh",
    email: "priya.singh@applywizz.com",
    role: "ceo",
  },
  {
    id: "3",
    name: "Amit Patel",
    email: "amit.patel@applywizz.com",
    role: "cxo",
  },
  {
    id: "4",
    name: "Sneha Reddy",
    email: "sneha.reddy@applywizz.com",
    role: "cxo",
  },
  {
    id: "5",
    name: "Vikram Sharma",
    email: "vikram.sharma@applywizz.com",
    role: "cxo",
  },
  {
    id: "6",
    name: "Admin User",
    email: "admin@applywizz.com",
    role: "admin",
  },
];

export const mockWallets: Wallet[] = [
  {
    userId: "3",
    userName: "Amit Patel (CMO)",
    allocated: 50000,
    companySpent: 32000,
    reimbursed: 8000,
    balance: 10000,
    proofPending: 5000,
  },
  {
    userId: "4",
    userName: "Sneha Reddy (CTO)",
    allocated: 75000,
    companySpent: 45000,
    reimbursed: 12000,
    balance: 18000,
    proofPending: 3000,
  },
  {
    userId: "5",
    userName: "Vikram Sharma (COO)",
    allocated: 60000,
    companySpent: 38000,
    reimbursed: 10000,
    balance: 12000,
    proofPending: 7000,
  },
];

export const mockExpenses: Expense[] = [
  {
    id: "EXP_01",
    userId: "3",
    userName: "Amit Patel",
    category: "Marketing",
    amount: 15000,
    source: "company",
    proofUrl: "/mock-invoice.pdf",
    status: "pending",
    submittedOn: new Date("2025-01-08"),
    notes: "Facebook Ads campaign",
  },
  {
    id: "EXP_02",
    userId: "4",
    userName: "Sneha Reddy",
    category: "Tech Infrastructure",
    amount: 25000,
    source: "company",
    proofUrl: "/mock-invoice.pdf",
    status: "approved",
    submittedOn: new Date("2025-01-07"),
    notes: "AWS hosting fees",
  },
  {
    id: "EXP_03",
    userId: "5",
    userName: "Vikram Sharma",
    category: "Travel",
    amount: 8000,
    source: "personal",
    proofUrl: "/mock-receipt.jpg",
    status: "proof_pending",
    submittedOn: new Date("2025-01-06"),
    notes: "Client meeting in Mumbai",
  },
  {
    id: "EXP_04",
    userId: "3",
    userName: "Amit Patel",
    category: "Office Supplies",
    amount: 3500,
    source: "company",
    status: "rejected",
    submittedOn: new Date("2025-01-05"),
    notes: "Stationery purchase",
    rejectionReason: "Missing proper invoice",
  },
  {
    id: "EXP_05",
    userId: "4",
    userName: "Sneha Reddy",
    category: "Software",
    amount: 12000,
    source: "company",
    proofUrl: "/mock-invoice.pdf",
    status: "pending",
    submittedOn: new Date("2025-01-09"),
    notes: "Figma annual subscription",
  },
];

export const mockCompanyExpenses: CompanyExpense[] = [
  {
    id: "CE001",
    type: "Salary",
    vendor: "Employee Payroll",
    amount: 850000,
    date: new Date("2025-01-01"),
    paymentRef: "PAY-JAN-2025",
    proofUrl: "/payroll-jan.pdf",
    notes: "January 2025 salaries",
  },
  {
    id: "CE002",
    type: "Rent",
    vendor: "Office Landlord",
    amount: 75000,
    date: new Date("2025-01-05"),
    paymentRef: "RENT-JAN-2025",
    proofUrl: "/rent-receipt.pdf",
    notes: "Monthly office rent",
  },
  {
    id: "CE003",
    type: "Tech Infrastructure",
    vendor: "AWS",
    amount: 45000,
    date: new Date("2025-01-10"),
    paymentRef: "AWS-INV-12345",
    proofUrl: "/aws-invoice.pdf",
    notes: "Cloud hosting",
  },
  {
    id: "CE004",
    type: "Utilities",
    vendor: "Electricity Board",
    amount: 12000,
    date: new Date("2025-01-08"),
    paymentRef: "ELEC-JAN-2025",
    proofUrl: "/electric-bill.pdf",
    notes: "Office electricity",
  },
  {
    id: "CE005",
    type: "Chocolates",
    vendor: "Sweet Shop",
    amount: 5000,
    date: new Date("2025-01-12"),
    paymentRef: "CHOC-001",
    proofUrl: "/chocolate-receipt.jpg",
    notes: "Employee appreciation chocolates",
  },
];